### ISSUE TITLE
[Quest] To Legion Hold

### ISSUE THREAD

**Issue by Anthonhed** [UberWoW335a/github#4]
To Legion Hold: Using quest item does not trigger quest dialog and on subsequent uses it turns you into an imp instead of a crate.

**Comment by Amrea** [comment]
Testing

**Comment by Amrea** [comment]
Quest 10563 (alli) and 10596 (horde) both give correct item, upon using it turns you into an imp instead of a box.

**Comment by MasterUberWoW** [comment]
I've added a fix to this issue. If anyone can test it for me upon next server restart that would be great.
